### ISSUE TITLE
sg dial

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/SG-Command#1]
Specifies your destination for networked gates.

**Comment by EpicKnarvik97** [comment]
The current implementation works, although the generation of tab completions is too slow to be usable. I'm not sure what exactly makes it so incredibly slow.

**Comment by EpicKnarvik97** [comment]
It was found to be a problem with the main plugin. Once the changes in https://github.com/stargate-rewritten/Stargate-Bukkit/commit/ee97ef8a69aaadf01df6c43d8dc53efd05536c1b is merged, the issue should be resolved.
